### ISSUE TITLE
Provide documentation on applying filters

### ISSUE THREAD

**Issue by cioace** [ghassani/ffstream#1]
Hi Ghassani, i tried to add my logo over video but doesn't  work.. how can i do?

**Comment by ghassani** [comment]
To apply a image overlay, use the filters in your playlist.json file. For an image which is applied to all videos in the playlist, add it to the root level "filters" array:

```
    "filters": [
		{
			'type': 'image_overlay',
			'kwargs: {},
			'animated': False,
			'image': '/path/to/image.png'
		}
    ],

```

If you wish to have the image overlay only be for a specific video in the playlist, you can just move the filter into the playlist entrty filters array:

entries: [
```
...

"filters": [
		{
			'type': 'image_overlay',
			'kwargs: {},
			'animated': False,
			'image': '/path/to/image.png'
		}
]

...
]
```


Check out https://github.com/ghassani/ffstream/blob/master/ffstream/filter.py for other types of filters available


You can use the filter entry kwargs to pass in custom options for the filter. In this case, the overlay filter is use ( if I remember correctly) https://ffmpeg.org/ffmpeg-filters.html#overlay-1

I will try to grab off my personal computer a better working example of filters in action when I have some time for now I hope this helps

**Comment by cioace** [comment]
Thanks so much for reply, but i solved that problem with logo. In your code: stream.py i added 

overlay = ffmpeg.input('/home/dragos/Desktop/logo.png')
video = ffmpeg.overlay(video, overlay, x=30, y=30)

And for 16:9 for each video i commented this:

#if probed_video_stream.resolution().x() < self.playlist().output().resolution().x():
			#video = video.filter('pad', self.playlist().output().resolution().x(), self.playlist().output().resolution().y(), '(ow-iw)/2', '(oh-ih)/2')

and i added something like this:
video = video.filter('setdar', '16/9')

Now i want to ask you something... I want the logo to stay the same size for each video, and each video even if it has a 4:3 size to be 16:9. Have you an ideea how to make that?

My solution is to create an new ffmpeg input with a fixed size for example 756x460 and to add that logo over this screen and try to increase width for each video.. but i don't know how to make that

**Comment by ghassani** [comment]
These settings can be defined within your playlist.json file and you do not have to edit the code to have those changes. The resolution can be set in the output structure in the playlist file:

https://github.com/ghassani/ffstream/blob/master/tests/data/playlist.json#L8

Although the additional filters you would have to program in.The better way would be to create your own filter by extending the Filter class in [ https://github.com/ghassani/ffstream/blob/master/ffstream/filter.py ] and then registering the filter early in the boot process [ https://github.com/ghassani/ffstream/blob/master/ffstream.py ], then reference them in your playlist json file



As far as size goes, you may have to play with the overlay filters options to get the desired effect. I have not tried that specifically so off the top of my head I am unsure but the ffmpeg documentation will be of help to you here.

**Comment by ghassani** [comment]
I am going to re-title the issue to remind me to add some documentation on this when i have time

**Comment by cioace** [comment]
> These settings can be defined within your playlist.json file and you do not have to edit the code to have those changes. The resolution can be set in the output structure in the playlist file:
> 
> https://github.com/ghassani/ffstream/blob/master/tests/data/playlist.json#L8
> 
> Although the additional filters you would have to program in.The better way would be to create your own filter by extending the Filter class in [ https://github.com/ghassani/ffstream/blob/master/ffstream/filter.py ] and then registering the filter early in the boot process [ https://github.com/ghassani/ffstream/blob/master/ffstream.py ], then reference them in your playlist json file
> 
> As far as size goes, you may have to play with the overlay filters options to get the desired effect. I have not tried that specifically so off the top of my head I am unsure but the ffmpeg documentation will be of help to you here.

Sure. 

I knew I could set them from the playlist, but I want to edit your code so I can edit the playlist without stopping stream. I would like the stream to go on infinite time.. And for that I wanted to know how to add the logo from the code.

**Comment by ghassani** [comment]
The solution that I used to keep the image the same size even though the various videos might be different sizes was to apply the padding to the video when the size of the video differs from the output (which looks like you commented out), but that might not be exactly what you want since that just padded black space around the sides and didnt stretch the video to fit the output resolution although you might want to play with that filter to get your desired effect

**Comment by ghassani** [comment]
Here is some filter examples:

`

    "filters": [
        {
            "type": "image_overlay",
            "options": {
                "image": "/path-to/ffstream-workspace/image.png",
                "kwargs": {
                    "x": "W-w-10",
                    "y": "10"
                }
            }
        },
        {
            "type": "video_info",
            "options": {
                "duration": 10,
                "interval": 600,
                "title_position": {
                    "x": 0,
                    "y": 20
                },
                "author_position": {
                    "x": 0,
                    "y": 100
                },
                "kwargs": {
                    "fontcolor": "#000000",
                    "bordercolor": "#ffffff",
                    "box": "1",
                    "boxcolor": "#2e51a3",
                    "boxborderw": 10,
                    "borderw": 5,
                    "fontsize": 40,
                    "fix_bounds": true,
                    "fontfile": "/path-to/ffstream-workspace/fonts/fontsDroidSans-Bold.ttf"
                }
            }
        },
        {
            "type": "interval_text",
            "options": {
                "duration": 10,
                "interval": 600,
                "text": "Welcome to the Stream.\r\nSome Other Words\r\nAnd More",
                "kwargs": {
                    "fontcolor": "#000000",
                    "bordercolor": "#ffffff",
                    "box": "1",
                    "boxcolor": "#2e51a3",
                    "boxborderw": 5,
                    "borderw": 2,
                    "fontsize": 20,
                    "fix_bounds": true,
                    "fontfile": "/path-to/ffstream-workspace/fonts/fontsDroidSans-Bold.ttf",
                    "x": "w-tw",
                    "y": "h-th"
                }
            }
        }
    ],

`

**Comment by cioace** [comment]
> Here is some filter examples:
> 
> `
> 
> ```
> "filters": [
>     {
>         "type": "image_overlay",
>         "options": {
>             "image": "/path-to/ffstream-workspace/image.png",
>             "kwargs": {
>                 "x": "W-w-10",
>                 "y": "10"
>             }
>         }
>     },
>     {
>         "type": "video_info",
>         "options": {
>             "duration": 10,
>             "interval": 600,
>             "title_position": {
>                 "x": 0,
>                 "y": 20
>             },
>             "author_position": {
>                 "x": 0,
>                 "y": 100
>             },
>             "kwargs": {
>                 "fontcolor": "#000000",
>                 "bordercolor": "#ffffff",
>                 "box": "1",
>                 "boxcolor": "#2e51a3",
>                 "boxborderw": 10,
>                 "borderw": 5,
>                 "fontsize": 40,
>                 "fix_bounds": true,
>                 "fontfile": "/path-to/ffstream-workspace/fonts/fontsDroidSans-Bold.ttf"
>             }
>         }
>     },
>     {
>         "type": "interval_text",
>         "options": {
>             "duration": 10,
>             "interval": 600,
>             "text": "Welcome to the Stream.\r\nSome Other Words\r\nAnd More",
>             "kwargs": {
>                 "fontcolor": "#000000",
>                 "bordercolor": "#ffffff",
>                 "box": "1",
>                 "boxcolor": "#2e51a3",
>                 "boxborderw": 5,
>                 "borderw": 2,
>                 "fontsize": 20,
>                 "fix_bounds": true,
>                 "fontfile": "/path-to/ffstream-workspace/fonts/fontsDroidSans-Bold.ttf",
>                 "x": "w-tw",
>                 "y": "h-th"
>             }
>         }
>     }
> ],
> ```
> 
> `

Thank you very much
